### ISSUE TITLE
Shadowlands Beta 

### ISSUE THREAD

**Issue by VaporAPX** [semlar/QuestPlates#1]
Hi there, I love this addon, use it all the time on live, can't live without it.  Recently had my account activated for the SL beta and this error pops up on load.

![questplates](https://user-images.githubusercontent.com/21989751/92080298-2d4a7680-ed76-11ea-8f79-1314e7bfb43c.jpg)

**Comment by BalurPoco** [comment]
I think I managed to fix it. I made a pull request.

**Comment by semlar** [comment]
Thanks guys, I went through the Shadowlands API changes and it looks like they reorganized the quest log functions under the C_QuestLog namespace, so any references to the old functions needed to be updated.

The merge request from @BalurPoco looks good so I've pushed it to curseforge, but let me know if you run into any other problems!
